development:
    dialect: sqlite3
    datasource: data/monparcours.db
    table: migrations

test_sqlite:
    dialect: sqlite3
    datasource: data/monparcours.db
    table: migrations
    statik: true

test_pg:
    dialect: postgres
    datasource: dbname=monparcours user=test password=test sslmode=disable
    table: migrations
    statik: true

test_mysql:
    dialect: mysql
    datasource: test:test@/monparcours?parseTime=true
    table: migrations
    statik: true

production:
    dialect: mysql
    datasource: test:test@/monparcours?parseTime=true
    table: migrations
    statik: true
